import { Roboto, Road_Rage } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavBar";

const roboto = Roboto({
  variable: "--font-roboto",
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
});

const roadrage = Road_Rage({
  variable: "--font-roadrage",
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${roadrage.variable} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
